# Generated by Django 4.2 on 2024-07-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_guru_app', '0005_career_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('profile_image', models.ImageField(upload_to='trainers/')),
                ('training_video', models.FileField(upload_to='trainers/videos/')),
            ],
        ),
    ]
