# Generated by Django 4.2 on 2024-07-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_guru_app', '0006_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='training_video',
            field=models.FileField(blank=True, null=True, upload_to='trainers/videos/'),
        ),
    ]
