# Generated by Django 4.2 on 2024-07-08 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_guru_app', '0011_alter_comment_comment_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_guru_app.career_model')),
            ],
        ),
    ]
