# Generated by Django 4.2 on 2024-07-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_guru_app', '0013_remove_career_model_post_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_model',
            name='end_date',
            field=models.DateField(),
        ),
    ]
