# Generated by Django 4.2 on 2024-07-21 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_guru_app', '0014_alter_career_model_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career_model',
            name='end_date',
        ),
        migrations.AddField(
            model_name='career_model',
            name='post_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
