# Generated by Django 5.1 on 2024-09-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_guru_app', '0016_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_model',
            name='job_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
